[project]
name = "example-multithreading"
version = "0.1.0"
description = "support de cours 5A SRI 2025-2026"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
